const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(process.env.UI_HTML||'customer-reschedule-normal-liff.html','utf8');
const src=html.match(/<script>\s*(\(function\(\)\{[\s\S]*?\}\)\(\));\s*<\/script>/)[1];new vm.Script(src);
function el(){return {value:'',dataset:{},options:[],children:[],disabled:false,hidden:false,classList:{s:new Set(['hidden']),add(x){this.s.add(x)},remove(x){this.s.delete(x)},contains(x){return this.s.has(x)}},addEventListener(){},append(x){this.children.push(x)},add(x){this.options.push(x);if(!this.value)this.value=x.value},set innerHTML(x){this.children=[];this.options=[];this.value=''},get innerHTML(){return ''},setAttribute(){},querySelector(sel){return this.children.find(x=>'.'+x.className===sel)||null}}}
async function start(status=403,search=''){let current=status,calls=[];const dom={};const node=id=>dom[id]||(dom[id]=el());const meals=[{slot:'lunch',name:'牛肉低碳（$220）',price:220},{slot:'dinner',name:'鷹嘴豆低碳（$180）',price:180}];const box={window:{__RESCHEDULE_RUNTIME__:{liffId:'test'},location:{origin:'http://localhost',search}},document:{getElementById:node,createElement:el},Option:function(text,value){this.text=text;this.value=value;this.dataset={}},liff:{init:async()=>{},isLoggedIn:()=>true,getIDToken:()=> 'synthetic',isInClient:()=>true},URLSearchParams,AbortController,setTimeout,clearTimeout,console,fetch:async url=>{calls.push(url);if(url==='/customer-reschedule/context')return {ok:true,status:200,json:async()=>({orders:[{order_id:'private-id',source_dates:[{date:'2026-10-01',label:'lunch $220',meals}],target_dates:['2026-10-29']}]})};if(url.includes('/preview'))return {ok:true,status:200,json:async()=>({source_date:'2026-10-01',target_date:'2026-10-29',source_meals:meals})};if(url==='/api/admin/customer-pair-reschedule-requests'){if(current==='network')throw Error('offline');return {ok:current===200||current==='malformed',status:current==='malformed'?200:current,json:async()=>current==='malformed'?{}:{requests:[{request_id:'secret-id',source_date:'2026-10-01',target_date:'2026-10-29',status:'pending_admin'}]}}}throw Error('unexpected endpoint '+url)}};
vm.createContext(box);vm.runInContext(src.replace('boot().catch(error => setText(result, String(error)))','globalThis.probe={refreshPending,statusText,formatMeals}; globalThis.ready=boot().catch(error=>{throw error})'),box);await box.ready;return {dom,box,calls,meals,setStatus:x=>{current=x}}}
(async()=>{let failed=0;async function test(name,fn){try{await fn();console.log('PASS',name)}catch(e){failed++;console.error('FAIL',name,e.message)}}
for(const s of [403,401,'network','malformed'])await test('initial denial '+s,async()=>{const x=await start(s);assert(x.calls.includes('/api/admin/customer-pair-reschedule-requests'));assert(x.dom.adminPanel.classList.contains('hidden'))});
await test('authorized admin positive control',async()=>{const x=await start(200);assert(!x.dom.adminPanel.classList.contains('hidden'));assert.equal(x.dom.pending.children.length,1)});
for(const s of [403,401,'network','malformed'])await test('admin then failed refresh '+s,async()=>{const x=await start(200);x.setStatus(s);await x.box.probe.refreshPending();assert(x.dom.adminPanel.classList.contains('hidden'));assert.equal(x.dom.pending.children.length,0)});
await test('customer display keeps full pair data',async()=>{const x=await start(403);assert.equal(x.dom.source.options[0].text,'2026-10-01 牛肉低碳、鷹嘴豆低碳');assert.deepEqual(JSON.parse(x.dom.source.options[0].dataset.meals),x.meals);assert(!/lunch|dinner|220|180|private-id/.test(x.dom.preview.textContent))});
await test('submitted is not completed',async()=>{const x=await start(403);assert.equal(x.box.probe.statusText('submitted'),'已送出待核准');assert(!x.box.probe.statusText('pending_admin').includes('完成'))});
await test('notification deep link is read only and selects request',async()=>{const x=await start(200,'?request_id=secret-id');assert(!x.calls.includes('/customer-reschedule/context'));assert.equal(x.dom.pending.children.length,1);assert.equal(x.dom.pending.children[0].dataset.requestId,'secret-id');assert(x.calls.every(u=>!u.includes('/approve')))});
await test('notification deep link denial remains hidden',async()=>{const x=await start(403,'?request_id=secret-id');assert(x.dom.adminPanel.classList.contains('hidden'));assert.equal(x.dom.pending.children.length,0)});
for (const [input,wanted] of [['雞肉低碳($185)','雞肉低碳'],['雞肉低碳（NT$1,200.50）','雞肉低碳'],['雞肉低碳 (＄185) ','雞肉低碳'],['雞肉低碳（TWD185）','雞肉低碳'],['雞肉低碳（低鹽）','雞肉低碳（低鹽）'],['雞肉150g（1份）','雞肉150g（1份）'],['雞肉低碳（$1,20）','雞肉低碳（$1,20）'],['（$185）','未提供']])await test('display-only price annotation '+input,async()=>{const x=await start(403);const data=[{slot:'lunch',name:input,price:185}];const saved=JSON.stringify(data);assert.equal(x.box.probe.formatMeals(data),wanted);assert.equal(JSON.stringify(data),saved)});
if(failed)process.exitCode=1;console.log('failed:',failed);
})().catch(e=>{console.error(e);process.exitCode=1});
