'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.textContent='';this.hidden=false;this.disabled=false;this.value='';this.style={};this.className='';}replaceChildren(...x){this.children=x}append(...x){this.children.push(...x)}addEventListener(t,h){(this.listeners[t]??=[]).push(h)}async dispatch(t){for(const h of this.listeners[t]||[])await h({type:t,target:this});await settle()}}
const walk=x=>[x,...x.children.flatMap(y=>y instanceof Element?walk(y):[])];const text=x=>x.textContent+x.children.map(y=>y instanceof Element?text(y):String(y)).join('');
const response=(body,status=200)=>({ok:status>=200&&status<300,status,json:async()=>body});const deferred=()=>{let resolve;return{promise:new Promise(r=>resolve=r),resolve}};async function settle(){for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r))}
const html=fs.readFileSync(process.argv[2],'utf8'), fixtures=JSON.parse(fs.readFileSync(process.argv[3],'utf8'));const script=html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];
function clock(){let now=0,n=0,timers=new Map();return{setTimeout(fn,ms){const id=++n;timers.set(id,{at:now+ms,fn});return id},clearTimeout(id){timers.delete(id)},advance(ms){now+=ms;for(const[id,t]of[...timers])if(t.at<=now){timers.delete(id);t.fn()}}}}
async function app(fetchImpl,{confirm=()=>true,fakeClock=null}={}){const ids={};for(const id of ['loading','error','errorTitle','errorCopy','empty','content','count','bar','statusCopy','windowText','days','nextCopy','backToLine','report','reportGood','reportPriority','reportNext','reportLimit','supplement','supplementTitle','supplementReason','supplementContent','supplementRequestedAt','submitSupplement','supplementSubmitState'])ids[id]=new Element(id==='submitSupplement'||id==='backToLine'?'button':'div');let uuid=0;const ctx={console,document:{getElementById:id=>ids[id],createElement:t=>new Element(t)},fetch:fetchImpl,AbortController,crypto:{randomUUID:()=>`customer-ui-${++uuid}`},setTimeout:fakeClock?fakeClock.setTimeout:setTimeout,clearTimeout:fakeClock?fakeClock.clearTimeout:clearTimeout,window:{confirm},liff:{init:async()=>{},isLoggedIn:()=>true,getIDToken:()=> 'customer-token',login(){},closeWindow(){}}};vm.runInNewContext(script,ctx);await settle();return{ids,ctx}}
async function actualFlow(){assert.match(html,/<h2 id="supplementTitle">請先完成指定紀錄<\/h2>/);let done=false,calls=[];const a=await app(async(path,o={})=>{calls.push({path,o});if(o.method==='POST'){done=true;return response(fixtures.post)}return response(done?fixtures.completed:fixtures.pending)});assert.equal(a.ids.statusCopy.textContent,'營養師需要你補充部分紀錄。');assert.equal(a.ids.supplementTitle.textContent,'請先完成指定紀錄');assert.ok(a.ids.supplementReason.textContent.includes(fixtures.pending.state.supplement_request.reason));assert.ok(a.ids.supplementContent.textContent.includes(fixtures.pending.state.supplement_request.required_content));await a.ids.submitSupplement.dispatch('click');const posts=calls.filter(x=>x.o.method==='POST');assert.equal(posts.length,1);assert.equal(posts[0].path,'/api/vip-health-check/me/supplement-completion');assert.deepEqual(JSON.parse(posts[0].o.body),{request_id:'customer-ui-1',expected_supplement_request_id:fixtures.pending.state.supplement_request.supplement_request_id,expected_source_token:fixtures.pending.state.supplement_request.expected_source_token});assert.ok(!Object.hasOwn(JSON.parse(posts[0].o.body),'user_id'));assert.equal(a.ids.statusCopy.textContent,'3 個有效日已完成，資料正在整理並等待營養師審核。');assert.equal(a.ids.supplementTitle.textContent,'補件已提交');assert.equal(a.ids.supplementSubmitState.textContent,'已提交，待營養師重新審查');assert.equal(a.ids.supplementReason.textContent,'');assert.equal(a.ids.supplementContent.textContent,'');assert.equal(a.ids.supplementRequestedAt.textContent,'');assert.equal(a.ids.supplement.hidden,false,'confirmed status remains visible');assert.equal(a.ids.submitSupplement.hidden,true,'confirmed completion hides duplicate action');assert.ok(!a.ids.supplementSubmitState.textContent.includes('核准'));const nextPending={...fixtures.pending,state:{...fixtures.pending.state,supplement_request:{...fixtures.pending.state.supplement_request,supplement_request_id:'req-next'}}};a.ctx.render(nextPending);assert.equal(a.ids.statusCopy.textContent,'營養師需要你補充部分紀錄。');assert.equal(a.ids.supplementTitle.textContent,'請先完成指定紀錄','a refreshed/new pending request resets submitted title');assert.equal(a.ids.supplementSubmitState.textContent,'');assert.equal(a.ids.supplement.hidden,false);assert.equal(a.ids.submitSupplement.hidden,false)}
async function negatives(){
 {let calls=[];const a=await app(async(p,o={})=>{calls.push({p,o});return response(fixtures.pending)},{confirm:()=>false});await a.ids.submitSupplement.dispatch('click');assert.equal(calls.filter(x=>x.o.method==='POST').length,0)}
 {const c=clock();let calls=[],attempt=0;const a=await app((p,o={})=>{calls.push({p,o});if(o.method==='POST')return ++attempt===1?new Promise(()=>{}):Promise.resolve(response({},503));return Promise.resolve(response(fixtures.pending))},{fakeClock:c});const first=a.ids.submitSupplement.dispatch('click');await settle();await a.ids.submitSupplement.dispatch('click');assert.equal(calls.filter(x=>x.o.method==='POST').length,1);c.advance(15000);await first;await a.ids.submitSupplement.dispatch('click');const bodies=calls.filter(x=>x.o.method==='POST').map(x=>x.o.body);assert.equal(bodies[1],bodies[0]);}
 {let calls=[];const a=await app(async(p,o={})=>{calls.push({p,o});return o.method==='POST'?response({},409):response(fixtures.pending)});await a.ids.submitSupplement.dispatch('click');assert.ok(a.ids.supplementSubmitState.textContent.includes('先補充紀錄'));assert.equal(calls.filter(x=>x.o.method==='POST').length,1);}
 for(const changed of [{...fixtures.completed,state:{...fixtures.completed.state,status:'needs_more_info'}},{...fixtures.completed,state:{...fixtures.completed.state,case_id:'other'}},{...fixtures.completed,state:{...fixtures.completed.state,supplement_request:fixtures.pending.state.supplement_request}}]){let posted=false;const a=await app(async(p,o={})=>{if(o.method==='POST'){posted=true;return response(fixtures.post)}return response(posted?changed:fixtures.pending)});await a.ids.submitSupplement.dispatch('click');assert.ok(a.ids.supplementSubmitState.textContent.includes('結果未知'));assert.ok(!a.ids.supplementSubmitState.textContent.includes('已提交'));assert.equal(a.ids.statusCopy.textContent,'營養師需要你補充部分紀錄。','an invalid canonical GET cannot paint the success hero');assert.equal(a.ids.supplementTitle.textContent,'請先完成指定紀錄','an invalid canonical GET cannot paint the submitted title');assert.equal(a.ids.submitSupplement.hidden,false)}
 {const pending=deferred();let getCount=0;const a=await app((p,o={})=>{if(o.method==='POST')return pending.promise;getCount++;return Promise.resolve(response(getCount===1?fixtures.pending:fixtures.completed))});const submit=a.ids.submitSupplement.dispatch('click');await settle();a.ctx.render(fixtures.completed);pending.resolve(response(fixtures.post));await submit;assert.ok(!a.ids.supplementSubmitState.textContent.includes('已提交'),'old view/app generation late POST cannot paint');}
 {const oldGet=deferred(),newPost=deferred();let getCount=0,postCount=0;const a=await app((p,o={})=>{if(o.method==='POST'){postCount++;return postCount===1?Promise.resolve(response(fixtures.post)):newPost.promise}getCount++;return getCount===1?Promise.resolve(response(fixtures.pending)):oldGet.promise});const oldSubmit=a.ids.submitSupplement.dispatch('click');await settle();assert.equal(postCount,1);a.ctx.render(fixtures.pending);const newSubmit=a.ids.submitSupplement.dispatch('click');await settle();assert.equal(postCount,2,'current generation can submit while stale canonical GET is pending');assert.equal(a.ids.submitSupplement.disabled,true,'new operation owns the busy lock');oldGet.resolve(response(fixtures.completed));await oldSubmit;assert.equal(a.ids.submitSupplement.disabled,true,'stale finally cannot clear the new operation lock');await a.ids.submitSupplement.dispatch('click');assert.equal(postCount,2,'new operation remains double-click guarded');newPost.resolve(response({},503));await newSubmit;assert.equal(a.ids.submitSupplement.disabled,false,'current operation releases its own lock');}
 {const attack='<img src=x onerror=alert(1)>';const hostile={...fixtures.pending,state:{...fixtures.pending.state,supplement_request:{...fixtures.pending.state.supplement_request,reason:attack}}};const a=await app(async()=>response(hostile));assert.ok(a.ids.supplementReason.textContent.includes(attack));assert.equal(walk(a.ids.supplementReason).filter(x=>x.tagName==='IMG').length,0)}
}
(async()=>{await actualFlow();await negatives();console.log('customer supplement completion LIFF: PASS')})().catch(e=>{console.error(e);process.exitCode=1});
